service: aws-serverless-express #Name of your App

provider:
  name: aws
  runtime: nodejs10.x # Node JS version
  memorySize: 512
  timeout: 15
  stage: production
  region: ap-south-1 # AWS region

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
    environment:
      DB_CONNECTION: mongodb+srv://admin:admin@cluster0.hhexi.mongodb.net/urldata?retryWrites=true&w=majority
